### ISSUE TITLE
Installation breaks because of new MySQL 8 login auth mechanism

### ISSUE THREAD

**Issue by tmikaeld** [atillay/craftcms3-docker#1]
https://stackoverflow.com/questions/49948350/phpmyadmin-on-mysql-8-0

![image 2018-04-27 at 2 14 42 pm](https://user-images.githubusercontent.com/907195/39362076-5b7bf5c0-4a25-11e8-805e-5644d632c414.png)

![image 2018-04-27 at 2 15 17 pm](https://user-images.githubusercontent.com/907195/39362096-6e008a26-4a25-11e8-9964-6ed1af282409.png)

**Comment by atillay** [comment]
Thanks for the report. I stuck the MySQL version to 5.7, the new version 8.x seems to introduce many breaking changes. You can pull and run docker-compose build :)

**Comment by tmikaeld** [comment]
Yeah, this is the first time I've encountered MySQL 8.x and I didn't have more time to dig into fixing it.

Thanks for setting it up with MySQL 5.x, it's good enough for development 👍
