### ISSUE TITLE
Default Database

### ISSUE THREAD

**Issue by vcao** [atillay/craftcms3-docker#2]
I'm experiencing that the initial database that is created is latin1_swedish_ci for both the craft and mysql database. Can the default be set to Craft documentation recommendations (utf8_unicode_ci)?
https://docs.craftcms.com/v3/installation.html#step-4-create-a-database

**Comment by atillay** [comment]
Done, you'll have to pull+recreate the mysql container (or just change encoding in PhpMyAdmin) https://github.com/atillay/craftcms3-docker#about-mysql-credentials
